name: PyDev.Debugger Release

on:
  push:
    branches:
      - "release-pydev-debugger-test"
    tags:
      - "pydev_debugger_*"
env:
    DISPLAY: ":99"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install common Python deps
        run: |
          pip install --upgrade pip
          pip install wheel cython psutil twine --no-warn-script-location
      - name: Check cython unchanged
        if: contains(matrix.name, 'checkbin')
        env:
          PYTHONPATH: .
        run: |
          python build_tools/build.py
          python build_tools/check_no_git_modifications.py
#     - name: Create cython binaries
#       if: contains(matrix.name, 'cython')
#       run: |
#         python setup.py sdist bdist_wheel
#     - name: Run Python 3.x tests
#       env:
#         # QT_DEBUG_PLUGINS: 1
#         PYTHONPATH: .
#         PYDEVD_USE_CYTHON: ${{matrix.PYDEVD_USE_CYTHON }}
#       run: |
#         python -m pytest -n auto -rfE

